## Pipeline stages
stages:
  - mavenbuild
#  - maventest
  - autodeploy
  - android-build

# build stage
maven-build:
  stage: mavenbuild
  tags:
    - shell
  script:
    - cd BackEnd
    - mvn clean install

# test stage
# maven-test:
#  stage: maventest
#  tags:
#    - shell
#  script:
#    - cd BackEnd
#    - mvn test
#  artifacts:
#    paths:
#      - BackEnd/target/*.jar

# autodeploy stage
autoDeploy:
  stage: autodeploy
  tags:
    - shell
  script:
    - cd BackEnd
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl daemon-reload
    - sudo systemctl start system-web-demo

# frontend android build
android-build:
  image: javiersantos/android-ci:latest
  stage: android-build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./FrontEnd/CyStudy/gradlew
  tags:
    - android
  script:
    - cd FrontEnd/CyStudy/
    - ./gradlew assemble
  artifacts:
    paths:
      - FrontEnd/CyStudy/app/build/outputs/

# Android unit tests
# frontend-unit-tests:
#   image: javiersantos/android-ci:latest
#   stage: frontend-unit-tests
#   before_script:
#     - export GRADLE_USER_HOME=`pwd`/.gradle
#     - chmod +x ./Frontend/CyStudy/gradlew
#   tags:
#     - android
#   script:
#     - cd FrontEnd/CyStudy/
#     - ./gradlew assemble
