package com.jr7.cystudy.model;

import javax.persistence.*;

/**
 * Model used for each class that has flashcards, and a user is registered for.
 *
 * @author Zach Gorman
 */
@Entity
@NamedQuery(name = "Classes.getClassByName", query = "SELECT c FROM Classes c WHERE c.className = ?1")
@Table(name="classes")
public class Classes {

    /**
     * Autogenerated id, which is the key to each object in the table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="class_id")
    private int classId;

    /**
     * name of the class
     */
    @Column(name="name")
    private String className;

    /**
     * Getter method to get the name of a class
     *
     * @return classname
     */
    public String getClassName(){
        return this.className;
    }

    /**
     * Setter method to set a classname for the model
     *
     * @param className name to set for the class being added to the model
     */
    public void setClassName(String className){
        this.className = className;
    }
}
