package com.jr7.cystudy.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@NamedQuery(
    name = "Stats.getStatsByUsernameAndClassName",
    query = "SELECT s FROM Stats s WHERE s.username = ?1 AND s.className =?2")
@Table(name = "stats")
public class Stats {

  /** Autogenerated id, which is the key to each object in the table. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private long id;

  /** username. name of user who's stats are being recorded. */
  @Column(name = "username")
  private String username;

  /** name of the class these stats are being generated for. */
  @Column(name = "class_name")
  private String className;

  /** Total number of questions attempted in a game. */
  @Column(name = "total", columnDefinition = "int default 0")
  private int totalQs;

  /** number of questions answered correctly. */
  @Column(name = "correct", columnDefinition = "int default 0")
  private int correctQs;

  /** total time spent studying for a class. */
  @Column(name = "time_spent", columnDefinition = "float default 0.0")
  private float time;

  /**
   * getter method for username.
   *
   * @return username
   */
  public String getUsername() {
    return this.username;
  }

  /**
   * Setter method to set a username.
   *
   * @param username self explanatory
   */
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * Getter method for the class_name.
   *
   * @return class_name
   */
  public String getClassName() {
    return this.className;
  }

  /**
   * setter method for className.
   *
   * @param name name of the class
   */
  public void setClassName(String name) {
    this.className = name;
  }

  /**
   * getter method for totalQs.
   *
   * @return total attempted questions
   */
  public int getTotal() {
    return this.totalQs;
  }

  /**
   * getter method for correctQs.
   *
   * @return total correctly attempted questions
   */
  public int getCorrect() {
    return this.correctQs;
  }

  /**
   * Setter method to add time to a user's current amount of time spent studying.
   *
   * @param t time to add to total
   */
  public void addTime(float t) {
    this.time += t;
  }

  /**
   * Getter method to retrieve the amount of time a student has spent studying.
   *
   * @return float of total time spent, retrieved from stats DB table
   */
  public float getTimeSpent() {
    return this.time;
  }
}
