package com.jr7.cystudy.model;

import javax.persistence.*;

/**
 * Class used for flashcards.
 *
 * @author Zach Gorman
 */
@Entity
@NamedQuery(
    name = "Terms.getTermsByClassName",
    query = "SELECT t FROM Terms t WHERE t.className = ?1")
@NamedQuery(
    name = "Terms.deleteCard",
    query = "DELETE FROM Terms t WHERE t.term = ?1 AND t.answer = ?2 AND t.className = ?3")
@Table(name = "terms")
public class Terms {

  /** Autogenerated id, which is the key to each object in the table. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private long id;

  /** name of the class that the term is used for */
  @Column(name = "class_name")
  private String className;

  /** name of the topic within a class that the term should be put into */
  @Column(name = "topic")
  private String topic;

  /** "question" part for the flashcard */
  @Column(name = "term")
  private String term;

  /** "answer" part for the flashcard */
  @Column(name = "answer")
  private String answer;

  /** time spent on a flashcard. used in stats */
  @Column(name = "time")
  private double timeSpent;

  /** default constructor */
  Terms() {}

  /**
   * Constructor when all of the information is known
   *
   * @param className name of the class that the term is used for
   * @param topic name of the topic within a class that the term should be put into
   * @param term "question" part for the flashcard
   * @param answer "answer" part for the flashcard
   */
  Terms(String className, String topic, String term, String answer) {
    this.className = className;
    this.topic = topic;
    this.term = term;
    this.answer = answer;
  }

  /**
   * Getter method to get the name of a Terms object
   *
   * @return classname
   */
  public String getClassName() {
    return this.className;
  }

  /**
   * Getter method to get the topic of a Terms object
   *
   * @return topic
   */
  public String getTopic() {
    return this.topic;
  }

  /**
   * Getter method to get the term of a Terms object
   *
   * @return term
   */
  public String getTerm() {
    return this.term;
  }

  /**
   * Getter method to get the answer of a Terms object
   *
   * @return answer
   */
  public String getAnswer() {
    return this.answer;
  }

  /**
   * Getter method to get the time spent on a card of a Terms object
   *
   * @return timeSpent
   */
  public double getTimeSpent() {
    return this.timeSpent;
  }
}
