package com.jr7.cystudy.model;

import javax.persistence.*;

@Entity
@NamedQuery(name = "User.getUserByUsername", query = "SELECT u FROM User u WHERE u.username = ?1")
@Table(name = "users")
public class User {

  /** Autogenerated id, which is the key to each object in the table. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private long id;

  /** username. pretty self explanatory */
  @Column(name = "username")
  private String username;

  /** BCrypt hashed password of the user */
  @Column(name = "password")
  private String password;

  /** The role of a user. Either student, teacher, or admin. */
  @Column(name = "role")
  private String role;

  /**
   * getter method to get the username of the User model
   *
   * @return username
   */
  public String getUsername() {
    return this.username;
  }

  /**
   * Setter method to set a username of a User model
   *
   * @param username self explanatory
   */
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * Getter method to get the hashed password of the user. used for login in {@link
   * com.jr7.cystudy.service.UserService} and {@link com.jr7.cystudy.controller.UserController}
   *
   * @return hashed password of user
   */
  public String getPassword() {
    return this.password;
  }

  /**
   * setter method to set hashed password of a user model
   *
   * @param pass hashed password to set
   */
  public void setPassword(String pass) {
    this.password = pass;
  }

  /**
   * getter method to get a user model's role
   *
   * @return role of user
   */
  public String getRole() {
    return this.role;
  }

  /**
   * Setter method to set the role of a user
   *
   * @param role string to set the user's role to
   */
  public void setRole(String role) {
    this.role = role;
  }
}
